# Generated by Django 5.1.2 on 2024-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_video_num_likes_alter_video_num_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Publicado em'),
        ),
    ]
